n_ion_species = 1
n_neutral_species = 1
boltzmann_electron_response = true
run_name = "2D-sound-wave_cheb-with-neutrals-manf"
evolve_moments_density = false
evolve_moments_parallel_flow = false
evolve_moments_parallel_pressure = false
evolve_moments_conservation = false
T_e = 1.0
rhostar = 1.0
initial_density1 = 0.5
initial_temperature1 = 1.0
initial_density2 = 0.5
initial_temperature2 = 1.0
z_IC_option1 = "sinusoid"
z_IC_density_amplitude1 = 0.001
z_IC_density_phase1 = 0.0
z_IC_upar_amplitude1 = 0.0
z_IC_upar_phase1 = 0.0
z_IC_temperature_amplitude1 = 0.0
z_IC_temperature_phase1 = 0.0
z_IC_option2 = "sinusoid"
z_IC_density_amplitude2 = 0.001
z_IC_density_phase2 = 0.0
z_IC_upar_amplitude2 = 0.0
z_IC_upar_phase2 = 0.0
z_IC_temperature_amplitude2 = 0.0
z_IC_temperature_phase2 = 0.0
charge_exchange_frequency = 1.0
ionization_frequency = 1.0
nstep = 1375
dt = 0.002
nwrite = 50
use_semi_lagrange = false
n_rk_stages = 4
split_operators = false

z_ngrid = 5
z_nelement = 2
z_bc = "periodic"
z_discretization = "chebyshev_pseudospectral"

r_ngrid = 5
r_nelement = 2
r_bc = "periodic"
r_discretization = "chebyshev_pseudospectral"

vpa_ngrid = 5
vpa_nelement = 8
vpa_L = 8.0
vpa_bc = "periodic"
vpa_discretization = "chebyshev_pseudospectral"

vperp_ngrid = 5
vperp_nelement = 8
vperp_L = 8.0
vperp_bc = "periodic"
#vperp_discretization = "finite_difference"
vperp_discretization = "chebyshev_pseudospectral"

gyrophase_ngrid = 5
gyrophase_nelement = 8

vz_ngrid = 5
vz_nelement = 8
vz_L = 8.0
vz_bc = "periodic"
vz_discretization = "chebyshev_pseudospectral"

vr_ngrid = 5
vr_nelement = 8
vr_L = 8.0
vr_bc = "periodic"
vr_discretization = "chebyshev_pseudospectral"

vzeta_ngrid = 5
vzeta_nelement = 8
vzeta_L = 8.0
vzeta_bc = "periodic"
vzeta_discretization = "chebyshev_pseudospectral"

[manufactured_solns]
use_for_advance = true
