n_ion_species = 1
n_neutral_species = 0
#boltzmann_electron_response = true
electron_physics = "boltzmann_electron_response"
evolve_moments_density = false
evolve_moments_parallel_flow = false
evolve_moments_parallel_pressure = false
evolve_moments_conservation = false
T_e = 1.0
T_wall = 1.0
initial_density1 = 1.0
initial_temperature1 = 1.0
z_IC_option1 = "gaussian"
z_IC_density_amplitude1 = 0.001
z_IC_density_phase1 = 0.0
z_IC_upar_amplitude1 = 0.0
z_IC_upar_phase1 = 0.0
z_IC_temperature_amplitude1 = 0.0
z_IC_temperature_phase1 = 0.0
vpa_IC_option1 = "gaussian"
vpa_IC_density_amplitude1 = 1.0
vpa_IC_density_phase1 = 0.0
vpa_IC_upar_amplitude1 = 0.0
vpa_IC_upar_phase1 = 0.0
vpa_IC_temperature_amplitude1 = 0.0
vpa_IC_temperature_phase1 = 0.0
initial_density2 = 1.0
initial_temperature2 = 1.0
z_IC_option2 = "gaussian"
z_IC_density_amplitude2 = 0.001
z_IC_density_phase2 = 0.0
z_IC_upar_amplitude2 = 0.0
z_IC_upar_phase2 = 0.0
z_IC_temperature_amplitude2 = 0.0
z_IC_temperature_phase2 = 0.0
vpa_IC_option2 = "gaussian"
vpa_IC_density_amplitude2 = 1.0
vpa_IC_density_phase2 = 0.0
vpa_IC_upar_amplitude2 = 0.0
vpa_IC_upar_phase2 = 0.0
vpa_IC_temperature_amplitude2 = 0.0
vpa_IC_temperature_phase2 = 0.0
charge_exchange_frequency = 0.0
ionization_frequency = 0.0
constant_ionization_rate = false
z_ngrid = 9
z_nelement = 3
z_bc = "wall"
z_discretization = "chebyshev_pseudospectral"
r_ngrid = 9
r_nelement = 3
r_bc = "periodic"
r_discretization = "chebyshev_pseudospectral"
vpa_ngrid = 16
vpa_nelement = 10
vpa_L = 8.0
vpa_bc = "periodic"
vpa_discretization = "chebyshev_pseudospectral"
vperp_ngrid = 8
vperp_nelement = 8
vperp_L = 8.0
vperp_discretization = "chebyshev_pseudospectral"

[timestepping]
nstep = 50
dt = 0.001
nwrite = 5
n_rk_stages = 4
split_operators = false

[manufactured_solns]
use_for_advance = true
