n_ion_species = 1
n_neutral_species = 1
boltzmann_electron_response = true
run_name = "nonlinear-sound-wave_fd_split3"
evolve_moments_density = true
evolve_moments_parallel_flow = true
evolve_moments_parallel_pressure = true
evolve_moments_conservation = true
T_e = 1.0
initial_density1 = 0.5
initial_temperature1 = 1.0
initial_density2 = 0.5
initial_temperature2 = 1.0
z_IC_option1 = "sinusoid"
z_IC_density_amplitude1 = 0.5
z_IC_density_phase1 = 0.0
z_IC_upar_amplitude1 = 0.0
z_IC_upar_phase1 = 0.0
z_IC_temperature_amplitude1 = 0.5
z_IC_temperature_phase1 = 3.14159265359
z_IC_option2 = "sinusoid"
z_IC_density_amplitude2 = 0.5
z_IC_density_phase2 = 3.14159265359
z_IC_upar_amplitude2 = 0.0
z_IC_upar_phase2 = 0.0
z_IC_temperature_amplitude2 = 0.5
z_IC_temperature_phase2 = 0.0
charge_exchange_frequency = 0.62831853071
ionization_frequency = 0.0
nstep = 2000
dt = 0.001
nwrite = 20
use_semi_lagrange = false
n_rk_stages = 4
split_operators = false
z_ngrid = 100
z_nelement = 1
z_bc = "periodic"
z_discretization = "finite_difference"
vpa_ngrid = 400
vpa_nelement = 1
vpa_L = 8.0
vpa_bc = "periodic"
vpa_discretization = "finite_difference"
