combine_outer = ["charge_exchange_frequency"]
n_ion_species = 1
n_neutral_species = 1
boltzmann_electron_response = true
evolve_moments_density = false
evolve_moments_parallel_flow = false
evolve_moments_parallel_pressure = false
evolve_moments_conservation = true
T_e = 1.0
initial_density1 = 1.0
initial_temperature1 = [0.25, 0.5, 1.0, 2.0, 4.0]
initial_density2 = 1.0
initial_temperature2 = [0.25, 0.5, 1.0, 2.0, 4.0]
z_IC_option1 = "sinusoid"
z_IC_density_amplitude1 = 0.01
z_IC_density_phase1 = 0.0
z_IC_upar_amplitude1 = 0.0
z_IC_upar_phase1 = 0.0
z_IC_temperature_amplitude1 = 0.0
z_IC_temperature_phase1 = 0.0
z_IC_option2 = "sinusoid"
z_IC_density_amplitude2 = 0.01
z_IC_density_phase2 = 0.0
z_IC_upar_amplitude2 = 0.0
z_IC_upar_phase2 = 0.0
z_IC_temperature_amplitude2 = 0.0
z_IC_temperature_phase2 = 0.0
charge_exchange_frequency = [0.0, 0.2, 0.4, 0.6, 0.8, 1.0, 1.2, 1.4, 1.6, 1.8, 2.0, 2.2, 2.4, 2.6, 2.8, 3.0, 3.2, 3.4, 3.6, 3.8, 4.0, 4.2, 4.4, 4.6, 4.8, 5.0, 5.2, 5.4, 5.6, 5.8, 6.0, 6.2, 6.4, 6.6, 6.8, 7.0, 7.2, 7.4, 7.6, 7.8, 8.0, 8.2, 8.4, 8.6, 8.8, 9.0, 9.2, 9.4, 9.6, 9.8, 10.0, 10.2, 10.4, 10.6, 10.8, 11.0, 11.2, 11.4, 11.6, 11.8, 12.0, 12.2, 12.4, 12.6, 12.8, 13.0, 13.2, 13.4, 13.6, 13.8, 14.0, 14.2, 14.4, 14.6, 14.8, 15.0, 15.2, 15.4, 15.6, 15.8, 16.0, 16.2, 16.4, 16.6, 16.8, 17.0, 17.2, 17.4, 17.6, 17.8, 18.0, 18.2, 18.4, 18.6, 18.8, 19.0, 19.2, 19.4, 19.6, 19.8, 20.0, 20.2, 20.4, 20.6, 20.8, 21.0, 21.2, 21.4, 21.6, 21.8, 22.0, 22.2, 22.4, 22.6, 22.8, 23.0, 23.2, 23.4, 23.6, 23.8, 24.0, 24.2, 24.4, 24.6, 24.8, 25.0]
ionization_frequency = 0.0
nstep = [1500, 1500, 1500, 800, 6000]
dt = [0.004, 0.00282842712474619, 0.002, 0.001414213562373095, 1.0e-4]
nwrite = 20
use_semi_lagrange = false
n_rk_stages = 4
split_operators = false
r_ngrid = 1
r_nelement = 1
z_ngrid = [9, 9, 9, 9, 17]
z_nelement = [2, 2, 2, 2, 8]
z_bc = "periodic"
z_discretization = "chebyshev_pseudospectral"
vpa_ngrid = 17
vpa_nelement = [8, 8, 8, 8, 64] #32
vpa_L = 16.0 #8.0
vpa_bc = "periodic"
vpa_discretization = "chebyshev_pseudospectral"
vz_ngrid = 17
vz_nelement = [8, 8, 8, 8, 64] #32
vz_L = 16.0 #8.0
vz_bc = "periodic"
vz_discretization = "chebyshev_pseudospectral"

[output]
#binary_format = "netcdf"
