name: Documentation

on:
  push:
    branches:
      - master
    tags: '*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@latest
        with:
          version: '1.10'
      - name: Install dependencies
        run: |
          pip3 install --user matplotlib
          julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=joinpath(pwd(), moment_kinetics))); Pkg.develop(PackageSpec(path=joinpath(pwd(), "makie_post_processing"))); Pkg.develop(PackageSpec(path=joinpath(pwd(), "plots_post_processing"))); Pkg.instantiate()'
      - name: Build and deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Authenticate with GitHub Actions token
        run: julia --project=docs/ docs/make.jl
