# Run all tests, which can take a long time
name: Long tests

# Only run when commits are added to master branch
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
      fail-fast: false
    timeout-minutes: 90

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1.8'
          arch: x64
      - uses: julia-actions/julia-buildpkg@v1
        env:
          # Use the system Python for PyCall - avoids library linking error on macOS
          PYTHON: "${{ env.pythonLocation }}/bin/python"
        # The following is copied and simplified from
        # https://github.com/julia-actions/julia-runtest/blob/master/action.yml
        # in order to pass customised arguments to `Pkg.test()`
        #
      - run: |
          pip3 install --user matplotlib
          julia --check-bounds=yes --color=yes --depwarn=yes --project=@. -e 'import Pkg; Pkg.test(; test_args=["--long"])'
        shell: bash
