# Based on example from https://github.com/julia-actions/julia-runtest
name: Run tests

on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
      fail-fast: false
    timeout-minutes: 50

    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1.9'
          arch: x64
      - uses: julia-actions/julia-buildpkg@v1
        with:
          project: 'moment_kinetics/'
      - uses: julia-actions/julia-runtest@v1
        with:
          project: 'moment_kinetics/'
